default_platform(:android)

platform :android do
  desc 'Build & upload Android bundle to Google Play'
  lane :release do
    ENV['GOOGLE_PLAY_TRACK'] ||= 'internal'
    sh('flutter pub get')
    sh('flutter build appbundle --target-platform android-arm64,android-arm --release')
    supply(
      json_key: 'fastlane/play-account.json',
      package_name: ENV.fetch('ANDROID_PACKAGE_NAME', 'com.xandera.canteen'),
      track: ENV.fetch('GOOGLE_PLAY_TRACK', 'internal'),
      aab: 'build/app/outputs/bundle/release/app-release.aab',
      skip_upload_changelogs: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
    )
  end
end

platform :ios do
  desc 'Build & upload iOS ipa to App Store Connect'
  lane :release do
    sh('flutter pub get')
    sh('flutter build ipa --release --export-options-plist ios/ExportOptions.plist')
    deliver(
      ipa: 'build/ios/ipa/Runner.ipa',
      app_identifier: ENV.fetch('IOS_BUNDLE_ID', 'com.xandera.canteen'),
      apple_id: ENV.fetch('APPLE_DEVELOPER_EMAIL', 'release@xandera.com'),
      api_key_path: 'fastlane/AuthKey.p8',
      api_key_id: ENV.fetch('APPLE_API_KEY_ID'),
      api_key_issuer_id: ENV.fetch('APPLE_API_ISSUER_ID'),
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
      precheck_include_in_app_purchases: false,
    )
  end
end
